language: python
sudo: false

env:
  - TOXENV=py27-django15
  - TOXENV=py27-django16
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py33-django15
  - TOXENV=py33-django16
  - TOXENV=py33-django17
  - TOXENV=py33-django18
  - TOXENV=py34-django15
  - TOXENV=py34-django16
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=pypy-django15
  - TOXENV=pypy-django16
  - TOXENV=pypy-django17
  - TOXENV=pypy-django18
  - TOXENV=py27-django19
  - TOXENV=py34-django19
  - TOXENV=py35-django19
  - TOXENV=pypy-django19

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install coverage
  - coverage report
